DROP DATABASE IF EXISTS FTC;
CREATE DATABASE FTC;

USE FTC; 
-- VE challenge for FTC

CREATE TABLE CARS(
make VARCHAR (255),
model VARCHAR(255),
year VARCHAR(255)
);


INSERT into CARS(make,model,year)
VALUES 
("Porsche", "gt3", "2021"),
("Lamborghini", "Huracan", "2021"),
("Porsche", "918", "2015");

INSERT into CARS (make, model, year)
VALUES
("Ferrari", "488", "2020"),
("Mitsubishi", "EVO", "2015");

SELECT  * FROM CARS;


-- EZ FOR FTC
CREATE TABLE BOOKS  (
PRIMARY KEY (id),
id INT NOT NULL AUTO_INCREMENT,
TITLE VARCHAR (255),
PUBLISHED_DATE  DATE,
AUTHOR VARCHAR(255)

);

INSERT into BOOKS (TITLE, PUBLISHED_DATE, AUTHOR)
VALUES
("Atomic Habits","2018-10-16","James Clear"),
("Hooked","2013-12-26","Nir Eyal"),
("Dont Make Me Think","2000-01-01","Steve Krug"),
("1984","1949-06-08","George Orwell"),
("Blink","2005-01-11","Malcolm Gladwell");

INSERT into BOOKS (TITLE, PUBLISHED_DATE, AUTHOR)
VALUES
("Outliers", "2008-11-18", "Malcolm Gladwell"),
("Contagious", "2013-03-05", "Jonah Berger");

SELECT * FROM BOOKS;

DELETE FROM BOOKS 
ORDER BY PUBLISHED_DATE LIMIT 1;

SELECT * FROM BOOKS;

SELECT id FROM BOOKS ORDER BY id DESC LIMIT 1 ;

-- MEDIUM FTC

CREATE TABLE MOVIES (
TITLE  VARCHAR (255),
RELEASE_DATE DATE,
RATING  VARCHAR(255)
);

INSERT INTO MOVIES (TITLE, RELEASE_DATE, RATING)
VALUES 
("BAD BOYZ FOR LIFE","2020-01-17","6.6"),
("THE IRON GIANT","1999-06-30","8"),
("THE ROAD TO EL DERADO","2000-03-31","6.9"),
("RUSH HOUR 2","2001-08-03","6.6"),
("RUSH HOUR","1998-09-18","7"),
("RUSH HOUR 3","2007-08-10","6.2"),
("BAD BOYS","1995-04-07","6.9"),
("BAD BOYS 2","2003-07-18","6.6"),
("NORBIT","2007-02-09","4.1"),
("THE FIFTH ELEMENT","1997-05-09","7.7");

SELECT * FROM MOVIES WHERE TITLE LIKE "%S%" ORDER BY RELEASE_DATE;

-- HARD FTC

ALTER TABLE MOVIES ADD FNAME VARCHAR (255);
ALTER TABLE MOVIES ADD LNAME VARCHAR (255);


UPDATE MOVIES SET FNAME = "Micheal", LNAME = "Bay" WHERE TITLE = "BAD BOYS" or TITLE = "BAD BOYS 2";
UPDATE MOVIES SET FNAME = "Bilall", LNAME="Fallah" WHERE TITLE = "BAD BOYZ FOR LIFE";
UPDATE MOVIES SET FNAME = "Brett", LNAME="Ratner" WHERE TITLE = "RUSH HOUR" or TITLE = "RUSH HOUR 2" or TITLE = "RUSH HOUR 3";
UPDATE MOVIES SET FNAME = "Luc", LNAME="Benson" WHERE TITLE = "THE FIFTH ELEMENT";
UPDATE MOVIES SET FNAME = "Brad", LNAME="Bird" WHERE TITLE = "THE IRON GIANT";
UPDATE MOVIES SET FNAME = "Bibo", LNAME="Bergeron" WHERE TITLE = "THE ROAD TO EL DERADO";
UPDATE MOVIES SET FNAME = "Brian", LNAME="Robbins" WHERE TITLE = "NORBIT";

SELECT CONCAT(FNAME, " ", LNAME) AS DIRECTOR_FULLNAME FROM MOVIES;

SELECT * FROM MOVIES ORDER BY LNAME; 
DELETE FROM MOVIES WHERE REGEXP_LIKE (LNAME,"[r-z]$");

SELECT * FROM MOVIES LIMIT 3;

-- VERRRY HARD FTC 

INSERT INTO CARS (make,model,year)
VALUES 
("Honda","Civic","1999"),
("Hyundai","Veloster","2013"),
("Ford","Mustang","2020");

ALTER TABLE CARS ADD COLOR VARCHAR (255);
ALTER TABLE CARS ADD PRICE INT (255);

UPDATE CARS SET COLOR = "BlACK", PRICE = 10000 WHERE model ="Civic";
UPDATE CARS SET COLOR = "MATTE BlACK", PRICE = 24000 WHERE model ="Veloster";
UPDATE CARS SET COLOR = "BlACK/RED", PRICE = 100000 WHERE model ="Mustang";


SELECT CONCAT (make, " ", model) AS SPECIFIC_CAR FROM CARS;

SELECT *, (SELECT COUNT(*) FROM CARS WHERE make = c.make) AS SAME_MAKE FROM CARS as c ; 


-- END OF FTC




































